sudo: required
dist: trusty
language: fortran

matrix:
  include:
    - os: linux
      compiler: gcc
      env: BTYPE=Release
#    - os: linux
#      compiler: clang
#      env: BTYPE=RelWithDebInfo
#    - os: linux
#      compiler: clang
#      env: BTYPE=Debug
#    - os: linux
#      compiler: gcc
#      env: BTYPE=Coverage
#    - os: osx
#      compiler: clang
#      env: BTYPE=RelWithDebInfo

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install gfortran; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install liblapack-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install fftw3; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install libfftw3-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install gcc; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install fftw --with-fortran; fi

install:
  - mkdir hosocean-build && cd hosocean-build
  # Configure
  - cmake $TRAVIS_BUILD_DIR/cmake -DCMAKE_BUILD_TYPE=$BTYPE -DCMAKE_INSTALL_PREFIX=~/hosocean
  # Build
  - make

script:
  # Test the program
  - make test
  # Create package
  - make package
  # Make sure we can install with no issues.
  - make install
#  # Create coverage report
#  - if [[ "$BTYPE" == "Coverage" ]];
#    then
#    echo "Coverage";
#    find $TRAVIS_BUILD_DIR -type f -name "*.gcno";
#    find $TRAVIS_BUILD_DIR -type f -name "*.gcna";
#    make coverage;
#    bash <(curl -s https://codecov.io/bash) -X gcov;
#    fi
